version: '3.6'
services:

  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_URL: postgres://admin:password@localhost:5432/fanz1st-media
      POSTGRES_DB: fanz1st-media
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  # Redis
  # redis:
  #   container_name: redismedia
  #   image: redis
  #   ports:
  #     - "6378:6378"

  # Backend
  fanz1st-media-api:
    # env_file:
    #   - ./.private/api-keys.env "Another way to insert env variables"
    container_name: fanz1st-media
    build: ./
    volumes:
      - ./:/usr/src/fanz1st-media-api
    command: npm start
    working_dir: /usr/src/fanz1st-media-api
    ports:
      - "5000:5000"
    environment:
      POSTGRES_URI: postgres://admin:password@postgres:5432/fanz1st-media
      REDIS_URI: redis://redis:6379
      
    links:
      - postgres
      # - redis
